### ISSUE TITLE
Abstract type results

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloogle.org#111]
Currently, the results for abstract types are little helpful. For example:

```clean
:: CompressSt
```

I propose a new syntax in search results using parentheses, to show the content of the type *and* show that it is abstract.

```clean
:: CompressSt (= { cs_pos :: !Int
                 , cs_bits :: !.{#Int}
                 })
```

This is similar to the way abstract synonyms are defined (e.g. `:: Number (:== Int)` tells the compiler to optimise with that information, but does not allow programmers to use the fact that a `Number` is just an `Int`).

Thoughts?

**Comment by dopefishh** [comment]
This is useful for when the actual type is available.

**Comment by camilstaps** [comment]
Perhaps this is not such a good idea, as people may think this is valid syntax / it may be unclear that it is an abstract type. People can click on the icl link if they need to see the implementation.

**Comment by dopefishh** [comment]
Maybe this is usefull to show, but it just has to made very clear that the syntax is invalid. For example by graying out the actual type, possibly with a hover message.

**Comment by camilstaps** [comment]
Greying out is a good idea. So much for my attempt to clean up the issues :smile:
