### ISSUE TITLE
Apps behaviour unexpected

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/cloogle.org#127]
The apps checkbox works fine when searching but there are still some discrepancies.

- [ ] Searching for `class toString` obviously shows the `toString` class with `196` instances which includes the apps...
- [ ] Secondly, when clicking on the `icl` text a `FileNotFoundError` occurs. When navigating to that file in the library viewer it does exist

**Comment by camilstaps** [comment]
This is probably because the apps don't use hierarchical module names and we don't store paths.
