### ISSUE TITLE
Transform queries before submitting

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloogle.org#128]
Some people search for e.g. `instance ==` or `Int -> String` (without `::`).

The frontend could recognise this and transform the query (change the input field) before submitting. I propose to start with these rules:

- `instance x` -> `class x`
- queries with spaces and `->` get `::` prepended

**Comment by dopefishh** [comment]
I disagree, a recommendation is fine but changing the query leads to unpredictable behaviour.

**Comment by camilstaps** [comment]
Not really, these are clear rules and queries with spaces are illegal anyway. There needs to be clear visual hinting however.

**Comment by dopefishh** [comment]
Maybe we can do client side input validation on the input field

**Comment by camilstaps** [comment]
That's fine with me too.
