### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloogle.org#129]
Currently, we use rigid relevance measures that are based on levenshtein distance (with slight modifications for substring matches) and the complexity of the unifier, where each type is given some complexity value that is rather arbitrary. We don't actually know if these measures help users find the functions they are looking for. For this it would be interesting to get some user feedback. This could also give some ideas for other features to include in the ranking function. For example, I think Platform should have higher relevance than CleanSnappy in general, but actual user data can help to find a proper ratio and way to implement that.

Concretely, I'm thinking about some button next to each search result on which users can click if the result is helpful. This information should then be stored in the database. After collecting a sufficient amount of data, we could look at fine-tuning the current measures, either manually by looking at cases where users used a low-ranked result or automatically by training some model that gives the actually used results higher positions.

Implementation-wise I'm thinking about adding a `id`, `request` and `response` columns to the `log` table, so that we have unique identifiers and full query/response information. The identifier is communicated to the frontend. When a user clicks the button, the browser makes a request that contains that identifier, the content and rank of the used result. A PHP session can be used to make sure this request actually comes from the same browser (and if we detect abuse, we can check using the rank/result data). (Let's be clear that this PHP session should be used for this only and will not be a requirement for the correct functioning of the frontend or the tracking of unique visitors.)

I think the button should have some inviting design (perhaps simply a unicode smiley or thumbs-up) but also be greyed-out to not distract. On mouse-over, a help text should explain what it does and why it's there. I think this design below is non-intrusive.

Any suggestions or complaints are welcome.

![2017-09-18-201838_347x317](https://user-images.githubusercontent.com/1202754/30557489-c5e60b5a-9cae-11e7-8d5a-7922ad489dbb.png)

**Comment by ErinvanderVeen** [comment]
Perhaps allowing the users to express that a result was not helpful would help too? Consider a situation where all results are decent, but one. A user will most likely not "upvote" (for lack of a better term) every decent result. So, instead, he/she could simply choose to "downvote" the unhelpful result.

**Comment by dopefishh** [comment]
It would be interesting to know what interests the user but I do think that the search results should be objective and rigid to provide consistent results. It would be strange if you send a query to someone and the results suddenly change...
This information about the suitability of a result is interesting to use for finetuning the current metrics.

**Comment by camilstaps** [comment]
Definitely, I do not intend to make search results user-dependent (even just because that would make the cache unusable).

**Comment by dopefishh** [comment]
Not only search results but also results order should be rigid, preferably documented and transparent

**Comment by camilstaps** [comment]
Yes, I consider the order to be part of the result.

**Comment by camilstaps** [comment]
I think this might be interesting, but seeing that only relatively few queries are interesting for this (those with `unify` set and coming from a browser) it is probably not going to give enough data to do anything meaningful - while implementing this would be quite some work.
