### ISSUE TITLE
Searching for syntax constructs

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloogle.org#130]
Cloogle does not index syntax constructs like `#`, `otherwise`, `:==`, or list/array-related sugar like `[x:xs]`, `<|-`, `[a,b..c]`, `.[i]`, `.[i,j]`, etc. Search data shows that this is something people are looking for. There currently is not a real way to include this information in the database, as these are not functions, types, classes, etc. (unlike 'builtins' like `File`, `if` and `TC` which *are* included).

There are several questions related to this:

- Do we extend the `CloogleDB` type with this non-indexable data, and if so, where do we put the database bootstrap information (currently in builddb for `if` etc.)? It might make more sense to put it in `CloogleDBFactory`.
- What should be shown in a search result? Ideally, some kind of documentation and some examples. But also, a link to the relevant section in the language report.
- This language report should then probably be accessible in a viewer similar to the library browser, a tree structure with the table of contents and a viewer that loads the HTML pages.
- Should we give constructs types? It might be helpful to give `.[i]` the type `{a} Int -> a`, however, we would want to use the same entry for `.[i,j]` with type `{{a}} Int Int -> a`. We could choose to use the simplest type, but that might be confusing. An other option is to create a fork of StdEnv with documentation, where functions like `select` and `_from_to` would get documentation to mention that there is sugar for them.
- How do we search for these constructs? For things like `#` and `:==` it seems straightforward (levenshtein distance), but for `[a,b..c]` and `.[i,j]` it's more complicated.

**Comment by dopefishh** [comment]
I like this.

A new result type should be added, `SyntaxResult` or something similar that contains untypable syntax constructs. Typeable syntax constructs can be added to the functions in my opinion. There are some difficulties. What to do with otherwise? It basically is `True` but can only be used in a guard. The same with `if`, it basically types as `Bool a a -> a` but can not be used in a higher order fashion.

**Comment by camilstaps** [comment]
Preview to allow for comments while the rest of the syntax is added:

> ![2017-09-27-180610_543x302](https://user-images.githubusercontent.com/1202754/30924284-986651ba-a3ae-11e7-805c-cc6f8e674265.png)

And the linked documentation:

> ![2017-09-27-180740_1888x806](https://user-images.githubusercontent.com/1202754/30924345-c5feec22-a3ae-11e7-8e5d-40d3a991aa05.png)
