### ISSUE TITLE
List of common errors / faults

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloogle.org#148]
I have long wanted to put together a list of common errors and faults on the Clean wiki or so, but perhaps Cloogle is the better place for it, as I see searches for some errors in the log.

What I have in mind is a new repository clean-cloogle/common-problems or so, with a single markdown file with a list of common problems. That file can be indexed in the frontend container when it is built, and when the search query matches any item from the list, the query is not sent to Cloogle but that result is returned instead. This is not an issue, because these errors typically have spaces in them (`type error`, `cannot unify types`, `bus error`, etc.) and Cloogle doesn't accept them as queries anyway. Alternatively, we can still run the query on Cloogle and do the search for errors on any request, interleaving the results, with the benefit that you can also search for one-word errors (so e.g. `type` would also give error results).

The result entry should link to the repository so that it encourages collaborative editing.

Thoughts?

**Comment by dopefishh** [comment]
Good idea, we can include common fixes. We should really think on how to treat OS errors like segfault and bus error though... They can have many causes and solutions.

**Comment by camilstaps** [comment]
Example for the 'heap full' problem:

![2017-11-02-120706_1592x609](https://user-images.githubusercontent.com/1202754/32322888-5bf3a550-bfc6-11e7-9168-7ec77a2bc873.png)
