### ISSUE TITLE
Add and expand documentation of syntax constructs

### ISSUE THREAD

**Issue by peterachten** [clean-cloogle/cloogle.org#180]
For some language elements documentation is incomplete or missing:

- [x] `*` (for uniqueness)
- [x] `:` (for uniqueness)
- [x] `[...]` (for uniqueness constraints)
- [x] `.` for uniqueness
- [x] `->` and `=` to separate pattern and alternative in `case` expressions
- [x] array comprehensions
- [x] `..` for extensible constructors
- [x] `|` for guards
- [x] `|` for class restrictions
- [x] `|` for record disambiguation in patterns and values
- [x] `&` (class restrictions)
- [x] `,` for type contexts
- [x] `::` for function and type definitions
- [x] `=` for function and type definitions
- [x] `=` and `=>` to separate guards and alternative
- [x] `special` for specialised class instances
- [x] `//` and `/* ... */` for comments
- [x] `=:` for constructor predicates (cf. https://gitlab.science.ru.nl/clean-and-itasks/iTasks-SDK/issues/220#note_47960)
- [x] `.` for hierarchical module names
- [x] `'...'.` for things imported quantifiedly

**Comment by camilstaps** [comment]
When I started adding these things I left out some of the most basic things, like guards, especially when they are heavily overloaded to not confuse people. But it probably makes sense to try to be as complete as possible instead of making an arbitrary choice as to what to in/exclude.

I added some more things that have to be added then (taken from #136).

**Comment by dopefishh** [comment]
https://cloogle.org/#%3C-%3A
Array comprehensions are already in the database

**Comment by camilstaps** [comment]
By array comprehension I meant `{.. \\ .. }`.

**Comment by camilstaps** [comment]
I worked through everything on the list. But if something is still missing, feel free to reopen or create a new issue/PR.
