### ISSUE TITLE
Docstring selection broken

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/cloogle.org#197]
The following query:
https://cloogle.org/#type%20Result

Shows some documentation, but that documentation is from the type appearing above it in the source:
https://cloogle.org/src/#Gast/Gast/Testable;line=29

When searching for the type the documentation is actually from, it is not displayed correctly either:
https://cloogle.org/#type%20Admin

Namely, the documentation of the last constructor is omitted.

**Comment by dopefishh** [comment]
Also, it is broken when a constructor has the same name as the type:
![html example](https://martlubbers.net/scr/2018-07-26_11-00-37.png)

**Comment by camilstaps** [comment]
Moved to https://gitlab.science.ru.nl/clean-and-itasks/clean-platform/issues/55
