### ISSUE TITLE
On Windows (Firefox), typing 'type Footballer' or 'class dist' removes ' ' from search text box

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloogle.org#210]
_From @peterachten on October 4, 2018 9:22_

On Windows 10 (Firefox), typing the query 'type Footballer' or 'class dist' removes ' ' from search text box, so that you end up with 'typeFootballer' and 'classdist'.

This does not happen with Microsoft Edge nor Chrome.

_Copied from original issue: clean-cloogle/Cloogle#15_

**Comment by camilstaps** [comment]
_From @dopefishh on October 4, 2018 9:25_

Can confirm for Firefox 62 on linux

**Comment by camilstaps** [comment]
_From @dopefishh on October 4, 2018 9:31_

The highlighter appears to output correct code:
```
highlightQuery('type Footballer')
"<span class=\"keyword\">type</span><span class=\"whitespace\"> </span><span class=\"type\">Footballer</span>"
```

So it probably has something to do with the input field mangling it.

**Comment by camilstaps** [comment]
This is probably related to https://github.com/clean-cloogle/cloogle.org/commit/4dc9851cb046f2b6871b6e9161d007496c473049 which sought to resolve other, more minor, issues with the input field. I'll have a look later today and fix it or otherwise revert that commit.

**Comment by dopefishh** [comment]
fun fact, this bug doesn't appear in Edge
