### ISSUE TITLE
Find usages

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloogle.org#52]
Would an option to search for all functions using a (list of) type(s) be useful?
For example, `fopen :: !{#Char} !Int !*f -> (!Bool, !*File, !*f)` is notoriously hard to find if you don't know that it gets an `Int` argument and returns a `Bool`. Then one may search for all functions with `String`, `*File` and `*World`.

On the backend, we may add a field to `Request`, e.g. `usingTypes :: Maybe [String]`.
On the frontend, we can use the syntax `[f] using t1 and t2 and ...`. I would rather not use `t1, t2, ...` since this has to be easily parseable in PHP and types may contain `,` but not `and` (with surrounding whitespace).

I don't think it is necessary to be able to combine the `usingTypes` field with other fields besides `name` (and `modules`, `libraries` and `page` of course).

-----

To do:

- [x] Usages of types (functions with the type in their type)
- [x] Usages of classes (functions with the class in the context *and* types with existential quantifiers and the class in their context *and* classes with this class in the context)
- [x] Usages of modules (imports, i.e., ModuleEntries - but we need to look in the icl)
- [x] Usages of functions (need to look into the icl for that)
- [x] <s>Better distance measure (e.g., usages from the same module/library should have lower distance?)</s> (this would be arbitrary)
- [x] Properly show `using` queries on the live statistics
- [x] Show `using` queries as a separate search type on the longterm statistics
- [x] If it turns out to be useful to be able to search for things using two types / classes / etc., we should probably make `using` a `Maybe [String]` and not allow `using type X` or `using type Y` but just `using X[, Y[, Z[..]]]`.
- [x] <s>Usages in instances. For instance, `fopen :: String Int *f -> *(Bool, *File, *f) | FileSystem f` should be returned for `using File, World` because there is an `instance FileSystem World`. In the result we should show the instance like a class, i.e. with members, but instantiate the member types.</s> For example:

  ```clean
  instance zero Int where zero :: Int
  ```
  ```clean
  instance Applicative Maybe
  where
      pure :: a -> Maybe a
      (<*>) infixl 4 :: (Maybe (a -> b)) (Maybe a) -> Maybe b
  ```

  This is not implemented, because it would require adding another constructor to `:: Result` and hence adaptations in all clients. Its benefits would be minor, because the instance/derivation lists are typically not so long and you can just scan those to see useful functions.

**Comment by camilstaps** [comment]
This can be generalised to finding the usages of any thing.

- For functions (incl. macros), the function implementations that contain them
- For types, the functions and type definitions that use them
- For modules, the modules where they are imported
- For classes,
  - the function implementations that contain their functions, and/or
  - the function types and type definitions that have them in the type context

**Comment by dopefishh** [comment]
It would be cool to have this in the most general way. Basically the preferred syntax would be to just prefix any query with `use:` or something.

- `use: module CleanSerial` would then show all files importing `CleanSerial`
- `use: :: (a->a) -> a` would show all files using a function with that signature
- `use: fix :: (a->a) -> a` would show all files using a function called `fix` with that signature
- `use: class Monad` would show all files using the Monad class
- `use: type TTYSettings` would show all files using that type
- `use: foldr` would show all files using a function called `foldr`

**Comment by camilstaps** [comment]
Yes, that's what I was thinking about too, forgot to mention it. OK on the syntax.

The options where you can find usages of functions with a certain type is not possible in general, because there can be two modules with the same name with the same function name with a different type.

**Comment by dopefishh** [comment]
that would indeed not be tractable.

**Comment by dopefishh** [comment]
Maybe we also want to find constructors with the last example.

**Comment by camilstaps** [comment]
Yes, and similarly for record fields. They should work like functions.

**Comment by camilstaps** [comment]
We should expand that syntax to be able to search for uses of multiple things at once. For example, `use: type Maybe, type Int` would search for functions that have both `Maybe` and `Int` in their type. 

But that's for later, the real difficulty here is accurately finding all uses and storing it space-efficiently.

**Comment by camilstaps** [comment]
Maps are balanced, so we can be sure they have a depth < 64. Therefore, we can represent positions in the map with a `:: DBIndex (:== Int)`, using bits for left and right. So, perhaps we could add a `tde_uses :: !{#DBIndex}` field to the `TypeDefEntry` and similarly for other entries, and add a `getFunctionByIndex :: DBIndex CloogleDB -> FunctionEntry`. For type safety, we should use separate `DBIndex` types for functions, types, classes, etc.

The `Request` can be extended to include a `uses :: Bool` field. If it is true, an exact search for the remaining should be conducted, and then the uses of the result should be looked up.

**Comment by dopefishh** [comment]
Indexing usages can just be a second sweep, maybe it should be stored in a second database, possibly even with a second backend.

**Comment by camilstaps** [comment]
I'm trying to avoid a second backend but if the database becomes too large that may indeed be necessary.

**Comment by camilstaps** [comment]
With the new array database, this is easier to implement. Just add a new `UsageEntry` with appropriate data, and link it to the other kinds of entries with `Index` lists. Then searching for a usage is (1) finding an exact match for the query and (2) using `getIndices` to get the usages.

**Comment by camilstaps** [comment]
The syntax is `using ...` and currently it is only possible for type definitions. So you can use either `using type Maybe` or `using Maybe`. In both cases, the name is matched exactly for efficiency.

To do:

- [x] Usages of types (functions with the type in their type)
- [ ] Usages of classes (functions with the class in the context *and* types with existential quantifiers and the class in their context)
- [ ] Usages of modules (imports)
- [ ] Usages of functions (need to look into the icl for that)
- [ ] Better distance measure (e.g., usages from the same module/library should have lower distance?)
