### ISSUE TITLE
Add statistics to `longterm.html`

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/cloogle.org#62]
It would be nice to have a small table showing some extremes such as:

- Highest number of unique visitors/requests on a certain day
- Average number of unique visitors/requests on a certain day
- etc...

**Comment by camilstaps** [comment]
Definitely. There are some more graphs that I wanted to add:

* Pie chart of OSs
* Average response time over time

I feel that perhaps we should redesign the page a bit to prevent cluttering it too much.

**Comment by camilstaps** [comment]
I tried the below, but even with indices on `ip` and `useragent_id` it takes really, really long. So unless I miss some simpler query I don't think we can add max. no. of unique visitors per day without adding metadata to the database.

```sql
SELECT number as maxn, thedate as maxd FROM
(
    SELECT DATE(`date`) as thedate,
        (SELECT COUNT(DISTINCT ip, useragent_id) FROM log where DATE(`date`)=thedate) as number
    FROM `log` GROUP BY DATE(`date`)
    ORDER BY number DESC, thedate DESC
) counts
```

**Comment by camilstaps** [comment]
Well *of course* there is a simpler query...
