### ISSUE TITLE
Local standalone operation

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloogle.org#66]
It would be nice to be able to use Cloogle locally. I imagine the following:

- A binary accepting queries in a string-format similar to `api.php`
- A setting for the search paths
- An easy way to rebuild the database, or perhaps only add one directory, to ease inclusion of libraries in development

Use cases:

- Offline usage
- Indexing of local development

Possibly this can also be embedded in [iClean](https://github.com/camilstaps/iclean), or, better, the Clean IDE.

**Comment by dopefishh** [comment]
This was also proposed by Rinus.

**Comment by camilstaps** [comment]
Several things need to be changed to get this to work:

- The cache should probably be disabled for offline usage. This solves many issues (with partially rebuilding the database, e.g.). It would be good if the cache can be lifted to the TCP server level, so that the CloogleServer does not depend on it.
- There should be a general function `:: Request TypeDB -> Response`. This is now hidden in the TCP server's handler.
- The builddb program shoud be integrated into the backend, with functions to regenerate parts of the TypeDB, e.g. `:: FilePath TypeDB *World -> *(TypeDB, *World)`. We should check if making the TypeDB unique improves performance (in the current implementation, this is not the case yet).
- It would probably be a good idea to rename this repository to clean-cloogle/cloogle.org and use clean-cloogle/cloogle for the non-TCP-specific backend. The backend in cloogle.org is then a simple wrapper around the cloogle backend.
- Pagination can be removed. It was added because JSON encoding can be slow on the server side and highlighting can be heavy on the client side. When the results are passed as a Clean object, neither of this is an issue. Removing the pagination will make implementing a client much easier. Ideally, pagination does not exist in the general backend and is added on a level below the TCP server in the cloogle.org backend.

**Comment by camilstaps** [comment]
I have split up the repository in three, which should make this easier.

- [libcloogle](https://github.com/clean-cloogle/libcloogle) contains the types that can be used as an interface to the TCP and HTTP servers. People can use this when they want to add an interface to the server to their project (the generic JSON functions make this straightforward).
- [Cloogle](https://github.com/clean-cloogle/Cloogle) contains the search functionality. People can use this when they want to run a Cloogle instance locally; it contains functions to search but also to build the type database.
- This repository provides a TCP wrapper around Cloogle, and CLI application to build the database.

@dopefishh has some doubts about whether libcloogle cannot be added to Cloogle, so this may still change.

I expect that several things have to be changed in the Cloogle modules to make it easy to use it in other projects, so let's say we're looking forward to pull requests.

Since these changes, it does not really make sense to have this issue here any more, but I'll leave it open anyway for discussion.

**Comment by camilstaps** [comment]
Looks like everything is in place for this. [cloogle-tags](https://github.com/clean-cloogle/cloogle-tags) shows how a program can be built that indexes Clean programs using Cloogle modules. For standalone operation, all that is needed is serialisation of the database (functions for this exist) and an index/search interface (depends on the requirements).
