### ISSUE TITLE
`class` instances not always correct

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/cloogle.org#96]
It seems that class instances don't work for higher kinded types that have instances for classes with a lowered kind.

For example take the [RWST](https://cloogle.org/#type%20RWST) which has kind `*->*->*->(*->*)->*->*` and implements classes such as [Functor](https://cloogle.org/#class%20Functor) where it is correctly listed as an instance but the instance it not listed on the page itself.

[Maybe](https://cloogle.org/#type%20Maybe) is an example of a higher kinded (`*->*`) type that does have the correct instances listed.

[Either](https://cloogle.org/#type%20Either) is another example of a higher kinded (`*->*->*`) type that has some instances listen(notably Bimap). Classes that require a kind `*->*` are not listed. The [Monad](https://cloogle.org/#class%20Monad) class is not listed here because it is not implemented by `Either` but by `Either a`.

We have three of such difficult cases.
- Instances with concrete types such as: `instance Monad (Either String)`
- Instances with types with class contexts such as: `instance Monad (Either a) | someClass a`
- Instances with only free type variables such as: `instance Monad (Either a)`

How do we solve this? I don't know. There are probably multiple solutions, one would be to add instances of the type with lower kinds (type variables already substituted) to the main screen.

Another solution would be to allow types to be added to higher kinded types. Thus allowing queries like `type Either String` or `type Maybe a`

Both solutions are no trivial to say the least.

**Comment by camilstaps** [comment]
Turns out the solution was trivial after all :smile:

Levenshtein distance 2.
